name: CI
on: [ push ]
jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Local PHP Security Checker
                uses: sh ./scripts/local-php-security-checker.sh
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v6
            -   name: PHPStan Static Analysis
                uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: max
